### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [cabbagelol/bfban-app-mobile#15]
请问可以发布到 F-Droid 吗？

**Comment by cabbagelol** [comment]
@linsui 可以的，但请自行重新编译并签名应用 :D

**Comment by linsui** [comment]
请问可以把 pubspec.lock 放到仓库里吗？ https://github.com/cabbagelol/bfban-app-mobile/blob/master/.gitignore#L26 以及为了方便自动更新，可以给每个版本打上 tag，并在仓库里指定 flutter 的版本吗？

**Comment by cabbagelol** [comment]
@linsui 当然可以,此[pr](https://github.com/cabbagelol/bfban-app-mobile/commit/eca5251a35de1debb785008c981e0ec603e21ad6)已添加pubspec.lock

在构建程序，对目标机器稍微指定版本,这由于其中部分包原因:
- flutter: 3.24.3
- dart 3.5.3
- flutter_elui_plugin
```yaml
  flutter_elui_plugin:
    path: ../flutter_elui_plugin
    git: https://github.com/cabbagelol/flutter-elui-plugin.git
```
